# Generated by Django 4.1.9 on 2023-06-29 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="update",
            new_name="updated",
        ),
    ]
