# Generated by Django 4.2.1 on 2023-06-30 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="postal_code",
            new_name="postal_codecity",
        ),
    ]
